name: 'sales_dbt_project'
version: '1.0.0'
profile: 'sales_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  sales_dbt_project:
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table

seeds:
  sales_dbt_project:
    +schema: raw
    +quote_columns: false

on-run-start:
  - "create schema if not exists bronze;"
  - "create schema if not exists silver;"
  - "create schema if not exists gold;"
  - "create schema if not exists analytics_raw;"