postgres_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-service
      user: dbt
      password: dbt
      port: 5432
      dbname: analytics
      schema: orders
    prod:
      type: postgres
      host: postgres-service
      user: dbt
      password: dbt
      port: 5432
      dbname: analytics
      schema: orders
